name: design_system
description: Design System - UI Components and Models
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # ユーティリティ
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^3.0.0

